### PR TITLE
Use json-stream instead of yajl-ruby to support for jruby

### PR DESCRIPTION
**Pull request by prashantvithani**

### CODE REVIEW

**Comment by zzet** [comment]
@prashantvithani Thanks for the PR. These changes make sense to me. 

But before the merge - could you remove merge-commits from your PR?

**Comment by prashantvithani** [comment]
@zzet done!

**Comment by zzet** [comment]
@prashantvithani new gem version released

**Comment by prashantvithani** [comment]
@zzet Thanks! I'm planning to use the same in https://github.com/FindHotel/bing-ads. I'll update the dependency there as well.

**Pull request merged**
